version: "3.4"

x-common:
  
  mongo-healthcheck: &mongo-healthcheck
    interval: 10s
    timeout: 5s
    retries: 5 
    test: "mongo localhost --eval 'quit(db.runCommand({ping:1}).ok ? 0 : 1)'"
  
  api-dev-volumes: &api-dev-volumes
    - ./mail/mail-verification-mail-template.html:/home/jetty/mail-verification-mail-template.html:ro
    - ./mail/mail-verification-mail-template.txt:/home/jetty/mail-verification-mail-template.txt:ro
    - ./mail/password-recovery-mail-template.txt:/home/jetty/password-recovery-mail-template.txt:ro
    - ./mail/mail.properties:/var/lib/jetty/mail.properties:ro
    - ./dev/mongo.properties:/var/lib/jetty/webapps/ROOT/WEB-INF/classes/mongo.properties:ro
    - api-previews:/var/data/envirocar/previews

  api-stable-volumes: &api-stable-volumes
    - ./mail/mail-verification-mail-template.html:/home/jetty/mail-verification-mail-template.html:ro
    - ./mail/mail-verification-mail-template.txt:/home/jetty/mail-verification-mail-template.txt:ro
    - ./mail/password-recovery-mail-template.txt:/home/jetty/password-recovery-mail-template.txt:ro
    - ./mail/mail.properties:/var/lib/jetty/mail.properties:ro
    - ./stable/mongo.properties:/var/lib/jetty/webapps/ROOT/WEB-INF/classes/mongo.properties:ro
    - api-previews:/var/data/envirocar/previews

  stable-api-environment: &stable-api-environment
    JAVA_OPTIONS: "-Djava.awt.headless=true"
  dev-api-environment: &dev-api-environment
    JAVA_OPTIONS: "-Djava.awt.headless=true"
    kafka.topic.measurement: dev-measurements
    kafka.topic.track: dev-tracks

  component-labels: &component-labels
    com.centurylinklabs.watchtower.enable: "true"

services:
  api-stable:
    container_name: api-stable
    image: envirocar/api:latest
    volumes: *api-stable-volumes
    networks:
      - stable
    environment: *stable-api-environment
    depends_on:
      - mongo-stable
    labels: *component-labels
    restart: unless-stopped
  
  api-anonymous-stable:
    container_name: api-anonymous-stable
    image: envirocar/api:anonymous
    volumes: *api-stable-volumes
    networks:
      - stable
    environment: *stable-api-environment
    depends_on:
      - mongo-stable
    labels: *component-labels
    restart: unless-stopped

  mongo-stable:
    container_name: mongo-stable
    image: mongo:4-xenial
    networks:
      - stable
    volumes:
      - ${MONGO_DATA}/stable/data:/data/db
      - ${MONGO_DATA}/stable/config:/data/configdb
    healthcheck: *mongo-healthcheck
    labels:
      - org.envirocar.backup.mongodb=enviroCar
    restart: unless-stopped

  api-dev:
    container_name: api-dev
    image: envirocar/api:dev
    volumes: *api-dev-volumes
    networks:
      - dev
    environment: *dev-api-environment
    depends_on:
      - mongo-dev
    labels: *component-labels
    restart: unless-stopped

  api-anonymous-dev:
    container_name: api-anonymous-dev
    image: envirocar/api:anonymous-dev
    volumes: *api-dev-volumes
    networks:
      - dev
    environment: *dev-api-environment
    depends_on:
      - mongo-dev
    labels:
      - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped

  mongo-dev:
    container_name: mongo-dev
    image: mongo:4-xenial
    networks:
      - dev
    volumes:
      - ${MONGO_DATA}/dev/data:/data/db
      - ${MONGO_DATA}/dev/config:/data/configdb
    healthcheck: *mongo-healthcheck
    labels:
      - org.envirocar.backup.mongodb=enviroCar
    restart: unless-stopped

  auth-proxy-stable:
    container_name: auth-proxy-stable
    image: envirocar/auth-proxy:latest
    depends_on:
      - api-stable
    networks:
      - stable
    environment:
      AUTH_PROXY_CONTEXT_PATH: /auth-proxy
      AUTH_PROXY_LOG_LEVEL: INFO
      AUTH_PROXY_TARGET_URI: https://${DOCKER_HOST_NAME}/api/stable/
    labels: *component-labels
    restart: unless-stopped

  auth-proxy-dev:
    container_name: auth-proxy-dev
    image: envirocar/auth-proxy:latest
    depends_on:
      - api-dev
    networks:
      - dev
    environment:
      AUTH_PROXY_CONTEXT_PATH: /auth-proxy-dev
      AUTH_PROXY_LOG_LEVEL: INFO
      AUTH_PROXY_TARGET_URI: https://${DOCKER_HOST_NAME}/api/dev/
    labels: *component-labels
    restart: unless-stopped

  webapp:
    container_name: webapp
    image: envirocar/webapp:latest
    depends_on:
      - auth-proxy-stable
    networks:
      - stable
    environment:
      EC_BASE_URL: https://${DOCKER_HOST_NAME}/auth-proxy/api
      EC_BASE: https://${DOCKER_HOST_NAME}/auth-proxy
      EC_WEBSITE_BASE: https://${DOCKER_HOST_NAME}/
      EC_SERVER_BASE: https://${DOCKER_HOST_NAME}/api/stable
    labels: *component-labels
    restart: unless-stopped

  landingpage:
    container_name: landing-page
    image: envirocar/landingpage:latest
    networks:
      - stable
    labels: *component-labels
    restart: unless-stopped

  citram-website:
    container_name: citram-website
    image: envirocar/citram-website:latest
    networks:
      - citram
    labels: *component-labels
    restart: unless-stopped

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_NOTIFICATIONS: slack
      WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL: ${WT_SLACK_WEBHOOK}
      WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER: watchtower
    networks:
      - infra
    command: --interval 30 --label-enable
    restart: unless-stopped

  proxy:
    container_name: proxy
    image: caddy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config
    networks:
      - dev
      - stable
      - citram
    restart: unless-stopped

volumes:
  caddy-data:
    driver: local
  caddy-config:
    driver: local
  api-previews:
    driver: local

networks:
  dev:
    driver: bridge
  stable:
    driver: bridge
  infra:
    driver: bridge
  citram:
    driver: bridge
