filebeat.inputs:
- type: docker
  paths:
   - '/var/lib/docker/containers/*/*.log'
  containers.ids: '*'

processors:
  - decode_json_fields:
      fields: ["message"]
      target: ""
      overwrite_keys: true
  - add_docker_metadata: ~

output.elasticsearch:
  hosts: ["elastic:9200"]

setup.kibana:
  host: "https://processing.envirocar.org/kibana"

logging.level: info
logging.to_stderr: true
logging.to_files: false
logging.to_syslog: false
