version: '3'
services:
  caddy-letsencrypt:
    build: 
      context: https://github.com/abiosoft/caddy-docker.git
      args: 
         plugins: filemanager,cors,ipfilter,realip,expires,cache
    image: custom-caddy

networks:
  shared:
    driver: bridge