version: '3'
services: 
  mapserver-db:
    image: mdillon/postgis
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mapserver
    volumes:
      - ./data/:/var/lib/postgresql/data
    networks: 
      - shared

  geoserver:
    image: kartoza/geoserver
    hostname: geoserver
    ports: 
      - 8089:8080
    depends_on:
      - mapserver-db
    networks:
      - shared

networks:
  shared:
    driver: bridge