version: "3"
services:
  docker:
    image: ${REGISTRY}/ec-cicd/docker:dind
    build: ./docker
    privileged: true
    depends_on:
      - registry
    command: --insecure-registry registry:5000 --bip 10.17.0.1/16
    volumes:
      - docker-certs:/certs
    networks:
      - shared

  jenkins:
    build:
      context: ./jenkins
    image: ${REGISTRY}/ec-cicd/jenkins:latest
    restart: always
    volumes:
      - ./jenkins/jobs:/usr/share/jenkins/jobs
      - docker-certs:/certs:ro
    environment:
      JENKINS_USERNAME: ${JENKINS_PASSWORD}
      JENKINS_PASSWORD: ${JENKINS_PASSWORD}
      JENKINS_OPTS: --prefix=/jenkins
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
    depends_on:
      - docker
    networks:
      - shared

  watchtower:
    image:  containrrr/watchtower:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --label-enable
    environment:
      WATCHTOWER_NOTIFICATIONS: slack
      WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL: ${WT_SLACK_WEBHOOK}
      WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER: watchtower
    networks:
      - shared

  registry:
    image: ${REGISTRY}/ec-cicd/registry:2
    build:
      context: ./registry
      args:
        REGISTRY_VERSION: 2
    restart: always
    ports:
      - 5000:5000
    networks:
      - shared
    volumes: 
      - registry-data:/var/lib/registry

volumes:
  docker-certs:
    driver: local
  registry-data:
    driver: local

networks:
  shared:
    driver: bridge
