version: "3"
services:
  docker:
    image: ${REGISTRY}/envirocar/docker:latest
    build: ./docker
    privileged: true
    depends_on:
      - registry
    command: --insecure-registry registry:5000 --bip 10.17.0.1/16
    volumes:
      - docker-certs:/certs
      - docker-data:/var/lib/docker
    networks:
      - shared
    restart: unless-stopped

  jenkins:
    image: ${REGISTRY}/envirocar/jenkins:latest
    build: ./jenkins
    volumes:
      - docker-certs:/certs:ro
      - jenkins-data:/var/jenkins_home
    environment:
      JENKINS_USERNAME: ${JENKINS_PASSWORD}
      JENKINS_PASSWORD: ${JENKINS_PASSWORD}
      JENKINS_OPTS: --prefix=/jenkins
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
      JOB_CONFIGS: |-
        auth-proxy,enviroCar Auth Proxy,enviroCar/auth-proxy
        dsm,enviroCar DSM API,enviroCar/enviroCar-server,dsm
        landingpage,enviroCar Landingpage,enviroCar/enviroCar-landing-page
        mms,enviroCar MapMatching API,enviroCar/enviroCar-mapmatching
        qad,enviroCar QAD service,enviroCar/qad
        usm,enviroCar USM API,enviroCar/enviroCar-server,usm
        webapp,enviroCar Webapp,enviroCar/envirocar-www-ng
        mss,enviroCar Mean Speed Service,enviroCar/mean-speed-service
    depends_on:
      - docker
    networks:
      - shared
    restart: unless-stopped

  registry:
    image: ${REGISTRY}/envirocar/registry:latest
    build: ./registry
    restart: always
    ports:
      - 127.0.0.1:5000:5000
    networks:
      - shared
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
    volumes: 
      - registry-data:/var/lib/registry
    restart: unless-stopped

  watchtower:
    image: ${REGISTRY}/envirocar/watchtower:latest
    build: ./watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_NOTIFICATIONS: slack
      WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL: ${WT_SLACK_WEBHOOK}
      WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER: watchtower
    networks:
      - shared
    restart: unless-stopped


volumes:
  docker-certs:
    driver: local
  docker-data:
    driver: local
  jenkins-data:
    driver: local
  registry-data:
    driver: local
    labels:
      org.envirocar.backup: "true"

networks:
  shared:
    driver: bridge
