version: "3"
services:
  ### GeoServer Setup
  geoserver:
    image: ${REGISTRY}/ec-components/geoserver:latest
    build: ./geoserver
    depends_on:
      - osm-db
    networks:
      - shared

  osm-db:
    image: ${REGISTRY}/ec-components/postgres:latest
    build: ./postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./osm-data:/var/lib/postgresql/data
    networks:
      - shared

  ### MapMatching Service
  mapmatching:
    image: ${REGISTRY}/ec-components/mapmatching:latest
    build:
      context: https://github.com/enviroCar/enviroCar-mapmatching.git#master
      dockerfile: docker/service/Dockerfile
    networks:
      - shared
    environment:
      - BAREFOOT_POSTGIS_HOST=osm-db
      - BAREFOOT_POSTGIS_PORT=5432
      - BAREFOOT_POSTGIS_DATABASE=${POSTGRES_DB}
      - BAREFOOT_POSTGIS_USER=${POSTGRES_USER}
      - BAREFOOT_POSTGIS_PASS=${POSTGRES_PASSWORD}
    depends_on:
      - osm-db
    labels:
      - com.centurylinklabs.watchtower.enable=true

  ### Data Management Service
  mongo-data:
    image: ${REGISTRY}/ec-components/mongo:latest
    build: ./mongo
    networks:
      - shared
    volumes:
      - mongo-data-data:/data

  dsm:
    image: ${REGISTRY}/ec-components/dsm:latest
    build:
      context: https://github.com/enviroCar/enviroCar-server.git#dsm
    volumes:
      - ./dsm/mail-verification-mail-template.html:/var/lib/jetty/mail-verification-mail-template.html:ro
      - ./dsm/mail-verification-mail-template.txt:/var/lib/jetty/mail-verification-mail-template.txt:ro
      - ./dsm/password-recovery-mail-template.txt:/var/lib/jetty/password-recovery-mail-template.txt:ro
      - ./dsm/mail.properties:/var/lib/jetty/mail.properties:ro
      - ./dsm/mongo.properties:/var/lib/jetty/webapps/ROOT/WEB-INF/classes/mongo.properties:ro
    networks:
      - shared
    environment:
      JAVA_OPTIONS: -Djava.awt.headless=true
    depends_on:
      - mongo-data
    labels:
      - com.centurylinklabs.watchtower.enable=true

  ### User Management Service
  mongo-user:
    image: ${REGISTRY}/ec-components/mongo:latest
    build: ./mongo
    networks:
      - shared
    volumes:
      - mongo-user-data:/data

  usm:
    image: ${REGISTRY}/ec-components/usm:latest
    build:
      context: https://github.com/enviroCar/enviroCar-server.git#usm
    volumes:
      - ./usm/mail-verification-mail-template.html:/var/lib/jetty/mail-verification-mail-template.html:ro
      - ./usm/mail-verification-mail-template.txt:/var/lib/jetty/mail-verification-mail-template.txt:ro
      - ./usm/password-recovery-mail-template.txt:/var/lib/jetty/password-recovery-mail-template.txt:ro
      - ./usm/mail.properties:/var/lib/jetty/mail.properties:ro
      - ./usm/mongo.properties:/var/lib/jetty/webapps/ROOT/WEB-INF/classes/mongo.properties:ro
    networks:
      - shared
    environment:
      JAVA_OPTIONS: -Djava.awt.headless=true
    depends_on:
      - mongo-user
    labels:
      - com.centurylinklabs.watchtower.enable=true

  auth-proxy:
    image: ${REGISTRY}/ec-components/auth-proxy:latest
    build:
      context: https://github.com/enviroCar/auth-proxy.git
    depends_on:
      - usm
      - dsm
    networks:
      - shared
    environment:
      AUTH_PROXY_CONTEXT_PATH: /auth-proxy
      AUTH_PROXY_LOG_LEVEL: INFO
      AUTH_PROXY_TARGET_URI: http://processing.envirocar.org/usm/
    labels:
      - com.centurylinklabs.watchtower.enable=true

  webapp:
    image: ${REGISTRY}/ec-components/webapp:latest
    build:
      context: https://github.com/enviroCar/envirocar-www-ng.git
    depends_on:
      - usm
      - dsm
    networks:
      - shared
    environment:
      EC_BASE_URL: https://envirocar.org/auth-proxy/api
      EC_BASE: https://envirocar.org/auth-proxy
      EC_WEBSITE_BASE: https://envirocar.org/
      EC_SERVER_BASE: https://envirocar.org/api/stable
    labels:
      - com.centurylinklabs.watchtower.enable=true

  landingpage:
    image: ${REGISTRY}/ec-components/landingpage:latest
    build:
      context: https://github.com/enviroCar/enviroCar-landing-page.git
    networks:
      - shared
    labels:
      - com.centurylinklabs.watchtower.enable=true

volumes:
  mongo-user-data:
    driver: local
  mongo-data-data:
    driver: local

networks:
  shared:
    driver: bridge
