version: "3"
services:
  ### GeoServer Setup
  geoserver:
    image: ${REGISTRY}/envirocar/geoserver:latest
    build: ./geoserver
    depends_on:
      - osm-db
    networks:
      - shared

  osm-db:
    image: ${REGISTRY}/envirocar/postgres:latest
    build: ./postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./osm-data:/var/lib/postgresql/data
    networks:
      - shared

  ### MapMatching Service
  mapmatching:
    image: ${REGISTRY}/envirocar/mapmatching:latest
    build:
      context: https://github.com/enviroCar/enviroCar-mapmatching.git#master
      dockerfile: docker/service/Dockerfile
    networks:
      - shared
    environment:
      - BAREFOOT_POSTGIS_HOST=osm-db
      - BAREFOOT_POSTGIS_PORT=5432
      - BAREFOOT_POSTGIS_DATABASE=${POSTGRES_DB}
      - BAREFOOT_POSTGIS_USER=${POSTGRES_USER}
      - BAREFOOT_POSTGIS_PASS=${POSTGRES_PASSWORD}
    depends_on:
      - osm-db
    labels:
      - com.centurylinklabs.watchtower.enable=true

  ### Data Management Service
  mongo-data:
    image: ${REGISTRY}/envirocar/mongo:latest
    build: ./mongo
    networks:
      - shared
    volumes:
      - mongo-data-data:/data

  dsm:
    image: ${REGISTRY}/envirocar/dsm:latest
    build: https://github.com/enviroCar/enviroCar-server.git#dsm
    volumes:
      - ./dsm/mail-verification-mail-template.html:/var/lib/jetty/mail-verification-mail-template.html:ro
      - ./dsm/mail-verification-mail-template.txt:/var/lib/jetty/mail-verification-mail-template.txt:ro
      - ./dsm/password-recovery-mail-template.txt:/var/lib/jetty/password-recovery-mail-template.txt:ro
      - ./dsm/mail.properties:/var/lib/jetty/mail.properties:ro
      - ./dsm/mongo.properties:/var/lib/jetty/webapps/ROOT/WEB-INF/classes/mongo.properties:ro
    networks:
      - shared
    environment:
      JAVA_OPTIONS: -Djava.awt.headless=true
    depends_on:
      - mongo-data
    labels:
      - com.centurylinklabs.watchtower.enable=true

  ### User Management Service
  mongo-user:
    image: ${REGISTRY}/envirocar/mongo:latest
    build: ./mongo
    networks:
      - shared
    volumes:
      - mongo-user-data:/data

  usm:
    image: ${REGISTRY}/envirocar/usm:latest
    build: https://github.com/enviroCar/enviroCar-server.git#usm
    volumes:
      - ./usm/mail-verification-mail-template.html:/var/lib/jetty/mail-verification-mail-template.html:ro
      - ./usm/mail-verification-mail-template.txt:/var/lib/jetty/mail-verification-mail-template.txt:ro
      - ./usm/password-recovery-mail-template.txt:/var/lib/jetty/password-recovery-mail-template.txt:ro
      - ./usm/mail.properties:/var/lib/jetty/mail.properties:ro
      - ./usm/mongo.properties:/var/lib/jetty/webapps/ROOT/WEB-INF/classes/mongo.properties:ro
    networks:
      - shared
    environment:
      JAVA_OPTIONS: -Djava.awt.headless=true
    depends_on:
      - mongo-user
    labels:
      - com.centurylinklabs.watchtower.enable=true

  auth-proxy:
    image: ${REGISTRY}/envirocar/auth-proxy:latest
    build: https://github.com/enviroCar/auth-proxy.git
    depends_on:
      - usm
      - dsm
    networks:
      - shared
    environment:
      AUTH_PROXY_CONTEXT_PATH: /auth-proxy
      AUTH_PROXY_LOG_LEVEL: INFO
      AUTH_PROXY_TARGET_URI: http://processing.envirocar.org/usm/
    labels:
      - com.centurylinklabs.watchtower.enable=true

  webapp:
    image: ${REGISTRY}/envirocar/webapp:latest
    build: https://github.com/enviroCar/envirocar-www-ng.git
    depends_on:
      - usm
      - dsm
    networks:
      - shared
    environment:
      EC_BASE_URL: https://envirocar.org/auth-proxy/api
      EC_BASE: https://envirocar.org/auth-proxy
      EC_WEBSITE_BASE: https://envirocar.org/
      EC_SERVER_BASE: https://envirocar.org/api/stable
    labels:
      - com.centurylinklabs.watchtower.enable=true

  landingpage:
    image: ${REGISTRY}/envirocar/landingpage:latest
    build: https://github.com/enviroCar/enviroCar-landing-page.git
    networks:
      - shared
    labels:
      - com.centurylinklabs.watchtower.enable=true

  mean-speed-service:
    image: ${REGISTRY}/envirocar/mean-speed-service:latest
    build: https://github.com/enviroCar/mean-speed-service.git
    depends_on:
      - osm-db
    networks:
      - shared
      - base_shared
    labels:
      - com.centurylinklabs.watchtower.enable=true
    environment:
      KAFKA_ENDPOINT: base_kafka_1:9092
      POSTGRES_HOST: osm-db
      POSTGRES_PORT: 5432
      POSTGRES_DBNAME: ${POSTGRES_DB}
      POSTGRES_USERNAME: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  qad:
    image: ${REGISTRY}/envirocar/qad:latest
    build: https://github.com/enviroCar/qad.git
    networks:
      - shared
      - base_shared
    labels:
      - com.centurylinklabs.watchtower.enable=true
    volumes:
      - base_ftp-data:/outputs
    environment:
      KAFKA_ENDPOINT: base_kafka_1:9092
      QAD_SIMPLIFY_LENGTH_CALCULATION: "false"
      QAD_MAX_ANGLE_DEVIATION: 90
      QAD_MAX_LENGTH_DEVIATION: 0.30
      QAD_SNAPPING_TOLERANCE: 20
      QAD_STOP_START_THRESHOLD: 5.0
      QAD_STOP_END_THRESHOLD: 10.0
      QAD_SEGMENT_BUFFER_SIZE: 20
      QAD_DENSIFY_NUM_POINTS: 4
      QAD_MAPMATCHING_ENABLE: "true"
      QAD_MAPMATCHING_ENDPOINT: https://processing.envirocar.org
      QAD_OUTPUT_PATH: /outputs

volumes:
  mongo-user-data:
    driver: local
  mongo-data-data:
    driver: local
  base_ftp-data:
    external: true

networks:
  shared:
    driver: bridge
  base_shared:
    external: true
