version: '3'
services: 
  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
    # - /home/.docker/config.json:/config.json
    command: --interval 30 --label-enable
    environment: 
      - WATCHTOWER_NOTIFICATIONS_T=slack
      - WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL_T=https://hooks.slack.com/##
      - WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER_T=watchtower
    networks:
      - shared
  registry:
    image: registry:2
    restart: always
    ports:
      - 5000:5000
    networks:
      - shared
networks:
  shared:
    driver: bridge