version: '3'
services: 
  
  ### ELK Stack
  elasticsearch:
    image: elasticsearch
    ports: 
    - 9200:9200
    - 9300:9300
    networks:
    - shared
    volumes:
    - ./data/elasticsearch:/usr/share/elasticsearch/data
  kibana:
    build: 
      context: ./kibana/
    image: ${REGISTRY}/ec-base/kibana
    ports:
    - 5601:5601
    environment:
    - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
    - elasticsearch
    networks:
    - shared
    labels:
    - com.centurylinklabs.watchtower.enable=true
  filebeat:
    build:
      context: ./filebeat/
    image: ${REGISTRY}/ec-base/filebeat
    user: root
    volumes:
    - /var/lib/docker/containers:/var/lib/docker/containers:ro
    - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
    - elasticsearch
    networks: 
    - shared
    labels:
    - com.centurylinklabs.watchtower.enable=true

networks:
  shared:
    driver: bridge