version: '3'
services: 
  ### Reverse Proxy
  caddy:
    build:
      context: ${PWD}/caddy
      args:
        plugins: cors,ipfilter,realip,expires,cache
    image: ${REGISTRY}/ec-proxy/caddy:latest
    ports:
      - 80:80
      - 443:443
      - 4443:4443
    volumes:
      - "./caddy/Caddyfile:/etc/Caddyfile"
      - "./.caddy:/root/.caddy"
    #- "./config/cert.pem:/etc/cert.pem"
    #- "./config/key.pem:/etc/key.pem"
    environment:
      - ACME_AGREE=true
    networks:
      - shared
      - ecbase_shared
      - ecbase_elk
      - eccicd_shared
      - eccomponents_ec-user-api
      - eccomponents_ec-data-api

networks:
  shared:
    driver: bridge
  ecbase_shared:
    external: true
  ecbase_elk:
    external: true
  eccicd_shared:
    external: true
  eccomponents_ec-user-api:
    external: true
  eccomponents_ec-data-api:
    external: true
