version: '3.4'
services: 
  caddy:
    image: ${REGISTRY}/envirocar/proxy:latest
    build:
      context: https://github.com/abiosoft/caddy-docker.git
      dockerfile: Dockerfile-no-stats
      args:
        plugins: cors,ipfilter,realip,expires,cache
    ports:
      - 80:80
      - 443:443
    #  - 4443:4443
    volumes:
      - ./caddy/Caddyfile:/etc/Caddyfile
      - certificates:/root/.caddy/acme/acme-v02.api.letsencrypt.org/sites/${DOCKER_HOST_NAME}/
      - caddy-root:/srv
      - caddy-data:/root/.caddy
    command: --conf /etc/Caddyfile --port 443 --log stdout--agree=true
    networks:
      - shared
      - base_shared
      - cicd_shared
      - components_shared
    restart: unless-stopped

volumes:
  certificates:
    driver: local
  caddy-data:
    driver: local
  caddy-root:
    driver: local

networks:
  shared:
    driver: bridge
  base_shared:
    external: true
  cicd_shared:
    external: true
  components_shared:
    external: true
