version: '3.4'
services: 
  caddy:
    image: ${REGISTRY}/ec-proxy/caddy:latest
    build:
      context: https://github.com/abiosoft/caddy-docker.git
      dockerfile: Dockerfile-no-stats
      args:
        plugins: cors,ipfilter,realip,expires,cache
    ports:
      - 80:80
      - 443:443
    #  - 4443:4443
    volumes:
      - ./caddy/Caddyfile:/etc/Caddyfile
      - caddy-data:/root/.caddy
    command:
      - "--conf"
      - "/etc/Caddyfile"
      - "--port"
      - "443"
      - "--log"
      - "stdout"
      - "--agree=true"
    networks:
      - shared
      - base_shared
      - cicd_shared
      - components_shared
    healthcheck:
      test: wget -q https://processing.envirocar.org/ -O - > /dev/null || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  caddy-data:
    driver: local

networks:
  shared:
    driver: bridge
  base_shared:
    external: true
  cicd_shared:
    external: true
  components_shared:
    external: true
