version: "3"
services:

  ### Kafka Stack
  zookeeper:
    image: ${REGISTRY}/envirocar/zookeeper:latest
    build: ./zookeeper
    networks:
      - shared

  kafka:
    image: ${REGISTRY}/envirocar/kafka:latest
    build: ./kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
    ports:
      - 9092:9092
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - shared

  ### ELK Stack
  elastic:
    image: ${REGISTRY}/envirocar/elastic:latest
    build: ./elastic
    networks:
      - shared
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: ${REGISTRY}/envirocar/kibana:latest
    build: ./kibana
    environment:
      - ELASTICSEARCH_URL=elastic:9200
    depends_on:
      - elastic
    networks:
      - shared

  filebeat:
    image: ${REGISTRY}/envirocar/filebeat:latest
    build: ./filebeat
    user: root
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - elastic
    networks:
      - shared

  ftp:
    image: ${REGISTRY}/envirocar/ftp:latest
    build: https://github.com/enviroCar/vsftpd-docker.git
    ports:
      - "20:20"
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - proxy_caddy-data:/var/lib/caddy
      - ftp-data:/srv/ftp
    environment:
      - CERT_FILE=/var/lib/caddy/acme/acme-v02.api.letsencrypt.org/sites/processing.envirocar.org/processing.envirocar.org.crt
      - CERT_KEY_FILE=/var/lib/caddy/acme/acme-v02.api.letsencrypt.org/sites/processing.envirocar.org/processing.envirocar.org.key
      - PASV_MIN_PORT=21100
      - PASV_MAX_PORT=21110
      - PASV_ADDRESS=processing.envirocar.org
      - PASV_ADDR_RESOLVE=YES
      - FTP_USER_NAME=ftpadmin
      - FTP_USER_PASS=${FTP_PASSWORD}
      - ALLOW_ANON=YES
    networks:
      - shared

volumes:
  elastic-data:
    driver: local
  kafka-data:
    driver: local
  ftp-data:
    driver: local
  proxy_caddy-data:
    external: true

networks:
  shared:
    driver: bridge

